### ISSUE TITLE
Feature Request: Reverse topological order / top down reading order

### ISSUE THREAD

**Issue by strokirk** [bwhmather/ssort#18] opened 2022-02-08 21:10 UTC
Hi,

Interesting project! I was wondering if there might be a place for a `--reverse` switch for this tool in the future?

The reason is that I generally write my code top-down, with the public API methods first in a class and the dependant methods / function below. This is to make it easier to read sections of the code - first you understand **what** a function will do, then you can read more about the **how**, rather than wondering why a specific private function will be used later.

See https://stackoverflow.com/a/36967648 for more discussion on ways to sort methods.

**Comment by bwhmather** [comment] 2022-02-08 22:36
I'm not opposed to the idea, but implementing it consistently would be very difficult.

The problem is that there are loads of places where bottom-up order is imposed by fact that python is a scripting language.  Things like decorators and base classes must be defined ahead of the things that consume them, and so must any of their dependencies.

Take the following example:
```python
def _shared_dep():
    ...

def _decorator(fn):
    _shared_dep()
    return fn

@_decorator
def top_level():
    _shared_dep()
```
In this case, `_shared_dep` must be defined before `top_level` is called.

Imports would also need to be special cased as most users will expect them to appear at the top, above the functions that depend on them.

**Comment by harrybiddle** [comment] 2022-03-18 09:17
I would love this option too :)

**Comment by bwhmather** [comment] 2023-12-29 23:01
Was keeping this open as a sticky, but I think the FAQ in the README does a better job of explaining why this isn't implemented.  Closing so as not to give the impression that this is likely to be possible.

**Closed by bwhmather** 2023-12-29 23:01 UTC
Labels: enhancement, help wanted, open challenge
